/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9247d8c0-7c41-4070-992d-7531e277e3e7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_P46uOdTPF",
    "aws_user_pools_web_client_id": "7f33o31rcb3fc1pibmkql045bi",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api85c594be",
            "endpoint": "https://1nazz9rwh9.execute-api.us-west-2.amazonaws.com/prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
