/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6f293090-460f-4169-910b-60e4392ebd54",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_u16CFpAcR",
    "aws_user_pools_web_client_id": "19tiijrk3bchlen24ka0rup02s",
    "oauth": {}
};


export default awsmobile;
